FROM jupyter/pyspark-notebook

# Install extra Python libraries
RUN pip install sqlalchemy psycopg2-binary pandas pyarrow

# Optional: Create config dir (but no need to write autosave setting)
RUN mkdir -p /home/jovyan/.jupyter

# Start the notebook with no token or password for dev
CMD ["start-notebook.sh", "--ServerApp.token=''", "--ServerApp.password=''"]
