FROM jupyter/pyspark-notebook

# Install extra Python libraries
RUN /opt/conda/bin/pip install sqlalchemy psycopg2-binary pandas pyarrow faker pyspark

# Optional: Create config dir
RUN mkdir -p /home/jovyan/.jupyter

# Start the notebook with no token or password for dev (overridden by compose command)
CMD ["start-notebook.sh", "--ServerApp.token=''", "--ServerApp.password=''"]