services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heartbeats_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    volumes:
      - grafana-storage:/var/lib/grafana

  producer:
    image: python:3.9
    volumes:
      - ./data_generator.py:/app/data_generator.py
    command: >
      bash -c "pip install confluent-kafka && python data_generator.py --interval 1"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

  consumer:
    image: python:3.9
    volumes:
      - ./consumer.py:/app/consumer.py
    command: >
      bash -c "pip install psycopg2-binary confluent-kafka && python consumer.py"
    depends_on:
      - postgres
      - kafka
    environment:
      - POSTGRES_HOST=postgres
      - KAFKA_BROKER=kafka:9092

volumes:
  postgres-data:
  grafana-storage:
